### ISSUE TITLE
Download link to releases is broken

### ISSUE THREAD

**Issue by nycnewman** [digital-asset/dablchat#20]

**Comment by dimitri-da** [comment]
Can you please specify which link are you referring to?
The latest release artifacts are here: https://github.com/digital-asset/dablchat/releases/latest and the links seem to work

**Comment by nycnewman** [comment]
Minor doc fix required in first step. Link to pre-created zip file references a no-longer valid filename

**Comment by dimitri-da** [comment]
yup makes sense. I had PR for it that I never merged: #16 . Should be good now
